parser: typescript-eslint-parser
extends:
  - standard
  - standard-react
rules:
  camelcase: "off"
  comma-dangle: "off"
  no-return-assign: "warn"
  operator-linebreak: "warn"
  eol-last: "warn"
  space-before-function-paren: "warn"
  space-in-parens: "warn"
  no-multiple-empty-lines: "warn"
  key-spacing: "warn"
  typescript/no-unused-vars: "error"
  no-undef: "off" # interface will error
  import/no-duplicates: "off"
  no-unused-vars: "warn"
  react/self-closing-comp: "warn"
plugins:
  - typescript
