dist: xenial

language: node_js
node_js:
  - "node"
  - "lts/*"

before_install:
  - cat /etc/os-release
  - uname -a
  - pwd
  - ls -lh

script:
  - npm run build && npm run minify

after_script:
  - ls -lh
  - tree temp/
