os:
  - linux
  - osx

dist: xenial

addons:
  apt:
    packages: tree

language: node_js
node_js:
  - "node"
  - "lts/*"

before_install:
  - cat /etc/os-release
  - uname -a
  - pwd
  - ls -lh

script:
  - npm run build && npm run minify

after_script:
  - ls -lh
  - tree temp/

jobs:
  include:
    - script: echo "Running unit job 1 ?"
    - script: echo "Running unit job 2 ?"
    - stage: GitHub Page Deploy
      script: echo "Deploying to GitHub Page ..."
      deploy:
        provider: pages
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        local-dir: ./temp/dist
        repo: Nullizer/nullizer.github.io
        on:
          branch: master
          # condition: $TRAVIS_OS_NAME = linux
          # node: node
