language: node_js
node_js:
  - lts/*

script:
  - npm run build && npm run minify

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./temp/dist
  repo: Nullizer/nullizer.github.io
  target-branch: master
  keep-history: true
  on:
    branch: master
