os:
  - linux
  - osx

dist: xenial

addons:
  apt:
    packages: tree

language: node_js
node_js:
  - "node"
  - "lts/*"

before_install:
  - uname -a
  - pwd
  - ls -lh

script:
  - npm run build && npm run minify

after_script:
  - tree -h temp/

before_deploy:
  - ls -lh

jobs:
  include:
    - stage: GitHub Page Deploy
      script: echo "Deploying to GitHub Page ..."
      deploy:
        provider: pages
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        local-dir: ./temp/dist
        repo: Nullizer/nullizer.github.io
        on:
          branch: master
          # condition: $TRAVIS_OS_NAME = linux
          # node: node
