dist: bionic
addons:
  apt:
    packages:
    - tree

language: node_js
node_js:
  - node

before_script:
  - npm ls --depth 0 || true

script:
  - npm run build && npm run minify

after_success:
  - tree -h temp/dist

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./temp/dist
  repo: Nullizer/nullizer.github.io
  target-branch: master
  keep-history: true
  on:
    branch: master
